Master
zedwick/BungeeChatFilter pull request #11
Opened 2017-04-08 10:25 UTC by leonfagan71

Added {message} to all command actions and alert

2017-04-08 11:07 UTC, zedwick commented
There's a lot of code repetition going on there. I had considered requesting you add the same to the other commands, but I couldn't think of a use case for the player sending a command which included their original message, for example. I decided it wasn't really needed.

However, if you'd like to make the placeholders available universally in all actions, we should have the logic in a single place so we don't have to maintain all these different lines of code to do the same thing.

2017-04-08 11:18 UTC, leonfagan71 commented
I agree, I'll probably make a function for it in a moment I'm just working
on a {match} which states the first word that is matched.

On Sat, Apr 8, 2017 at 12:07 PM, zedwick <notifications@github.com> wrote:

> There's a lot of code repetition going on there. I had considered
> requesting you add the same to the other commands, but I couldn't think of
> a use case for the player sending a command which included their original
> message, for example. I decided it wasn't really needed.
>
> However, if you'd like to make the placeholders available universally in
> all actions, we should have the logic in a single place so we don't have to
> maintain all these different lines of code to do the same thing.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zedwick/BungeeChatFilter/pull/11#issuecomment-292711046>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AG4O2NHU2SqfLptlv4XHSDICR24lA6B-ks5rt2pagaJpZM4M3qay>
> .
>

2017-04-08 12:15 UTC, leonfagan71 commented
Made it a function, simpler to change things.
{match} = word that matched to cause issue.
{message} = will display the message or command used
{player} = will display the playername

Example:
message: "{player}, you said '{match}' when saying {message}"

2017-04-08 12:23 UTC, zedwick requested changes
You seem to have duplicated config.yml and plugin.yml into the root, could you remove those please.

2017-04-08 12:45 UTC, leonfagan71 commented
I've removed plugin.yml and config.yml from the root, 
plugin.yml does cause an issue for me and requires it to be there, I've updated .gitignore for this to not be noticed in the future.

2017-04-08 13:30 UTC, zedwick commented
Which IDE do you use? If you can open the project as a maven project, the pom.xml should provide the proper location for the plugin.yml and config.yml.

I think I'd prefer it if you didn't add little workarounds like that to the .gitignore. You can always add it to your local .gitignore if you want to still do that.

2017-04-08 13:56 UTC, leonfagan71 commented
Eclipse Java EE IDE.
For some reason it's ignoring the pom.xml file or it does not specify it in
it.
I will attempt to remove the global .gitignore and just use it locally.

Regards.

On Sat, Apr 8, 2017 at 2:30 PM, zedwick <notifications@github.com> wrote:

> Which IDE do you use? If you can open the project as a maven project, the
> pom.xml should provide the proper location for the plugin.yml and
> config.yml.
>
> I think I'd prefer it if you didn't add little workarounds like that to
> the .gitignore. You can always add it to your local .gitignore if you want
> to still do that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zedwick/BungeeChatFilter/pull/11#issuecomment-292718220>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AG4O2J4XUfvhkPIvPFuMl1gRhkEMAdtEks5rt4vwgaJpZM4M3qay>
> .
>

2017-04-08 15:21 UTC, leonfagan71 commented
Ahh, It looks like I was exporting instead of using Maven,
Issues resolved now.

2017-04-08 18:08 UTC, zedwick requested changes
Got some changes for you to make before I can accept this, but once they're done should be ready.

2017-04-08 18:08 UTC, zedwick commented on .gitignore
> +plugin.yml
Remove plugin.yml line

2017-04-08 18:08 UTC, zedwick commented on src/main/java/com/minecraftdimensions/bungeechatfilter/Rule.java
> +    	return m.group(1) ;
remove space here

2017-04-08 18:08 UTC, zedwick commented on src/main/resources/plugin.yml
> -website: https://www.spigotmc.org/resources/bungeechatfilter.20596/
Don't remove plugin.yml file.

2017-04-08 18:08 UTC, zedwick commented on src/main/java/com/minecraftdimensions/bungeechatfilter/Rule.java
> +
Remove unused comment/line

2017-04-08 18:08 UTC, zedwick commented on src/main/java/com/minecraftdimensions/bungeechatfilter/Rule.java
> +                	rp =rp.replace("{arguments}", message.split( " ", 2 )[1] )    ;
I know it was there before, but could you remove the whitespace before the `;`

2017-04-09 21:17 UTC, leonfagan71 commented
Have made those changes, any more to recommend?

2017-04-10 14:11 UTC, zedwick approved these changes

2017-04-10 14:15 UTC, zedwick requested changes
Could you please undo the changes to the whitespace at the beginning of all lines in Rule.java. The rest of the project uses spaces, where-as you have switched the lines in this file to tabs.

2017-04-10 14:32 UTC, leonfagan71 commented
Like that? 
all tabs replaced with spaces.
chucked it through a few syntax fixers to sort indentations and remove whitespace, that's why tabs existed.

2017-04-10 15:31 UTC, zedwick commented
Right, I see.
Now I can see that a lot of the other original whitespace has been removed, the project has spaces inserted for readability (I assumed) throughout. I'm not necessarily completely opposed to that changing, but it shouldn't be part of this PR and should be applied throughout the project.

It also makes it difficult to easily see which lines of code has been changed, as I am seeing a lot of other unrelated lines changed due to the spaces being removed.

2017-04-11 07:35 UTC, leonfagan71 commented
Okay, I understand, 
I'm fairly new to GitHub in terms of actually adding to repositories,
I'll see if I can go back a bit.

2017-04-11 11:29 UTC, zedwick commented
No worries.

2017-04-12 20:15 UTC, closed without merging