Added CustomParams
zedwick/BungeeChatFilter pull request #12
Opened 2017-04-12 20:30 UTC by leonfagan71

2017-04-12 20:32 UTC, leonfagan71 commented
Should not have edited entire file now.
Added {message}, {match} and {player} to most action output types.

2017-04-12 21:03 UTC, zedwick requested changes
You've still removed a ton of spaces in lines you didn't need to modify.

2017-04-12 21:03 UTC, zedwick commented on src/main/java/com/minecraftdimensions/bungeechatfilter/Rule.java
> +        return regex.matcher(message);
Why did you modify these lines?

2017-04-12 21:03 UTC, zedwick commented on src/main/java/com/minecraftdimensions/bungeechatfilter/Rule.java
> +        return getMatcher(message).find();
Another example of lines modified to remove spaces, with not code changes.

2017-04-12 21:03 UTC, zedwick commented on src/main/java/com/minecraftdimensions/bungeechatfilter/Rule.java
> +            if (action.equals("deny")) {
I can see that these lines at the top have just been reformatted again, which makes it difficult to easily read the actual changes made in this block of changed lines (and we don't want you reformatting the code in this PR)

2017-04-12 21:07 UTC, zedwick commented on src/main/java/com/minecraftdimensions/bungeechatfilter/Rule.java
> +            if (action.equals("deny")) {
I did not comment on all the lines you've reformatted, please try to ensure your commit is only changing the lines needed for your feature contribution.

2017-04-12 21:18 UTC, leonfagan71 commented
I essentially just created a new pull request and coped the files I was working on before into the directory.
you asked me to remove spaces in the last pull request so I ran it through a formatter, it fixed the indentation issues that made it harder to understand. it was then filled with tabs instead of spaces so I replaced them.

At this point there was a ton of code changes so I closed the PR and created this one.
I don't really have enough time to keep making changes to make it look worse than before.
Extra spaces and new lines just look terrible, yes it can sometimes help people to see what's going on but for most of these functions, you don't really need to have them.
New line 83 is the only example where it's harder to work out what's going on with that line.

2017-04-13 02:11 UTC, zedwick commented
Making frivolous formatting changes to a file by running it blindly through a formatter out of laziness just to avoid changing 2/3 lines by hand is not an ideal way to contribute code to a project, as stated.

Thank you for taking the time to make these PRs. I'll likely come back to read through them at some point when I come to implement the feature.

2017-04-13 02:11 UTC, closed without merging